################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
SX_SRCS := 
PP_SRCS := 
CC_SRCS := 
FSY_SRCS := 
P_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
P_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
CXX_DEPS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
mbed-gr-libs/AsciiFont \
mbed-gr-libs/DisplayApp \
mbed-gr-libs/EasyAttach_CameraAndLCD \
mbed-gr-libs/EasyPlayback \
mbed-gr-libs/EasyPlayback/decoder \
mbed-gr-libs/GR-PEACH_video \
mbed-gr-libs/GR-PEACH_video/targets/TARGET_RZ_A1XX/TARGET_RZA1UL/drivers/vdc5/src \
mbed-gr-libs/GR-PEACH_video/targets/TARGET_RZ_A1XX/TARGET_RZA1UL \
mbed-gr-libs/GR-PEACH_video/targets/TARGET_RZ_A1XX/drivers/ceu/src \
mbed-gr-libs/GR-PEACH_video/targets/TARGET_RZ_A1XX/drivers/ceu/userdef \
mbed-gr-libs/GraphicsFramework/jcu/jcu_driver \
mbed-gr-libs/GraphicsFramework/jcu/jcu_driver/TARGET_RZ_A1XX \
mbed-gr-libs/GraphicsFramework/jcu/porting \
mbed-gr-libs/GraphicsFramework/jcu/userdef \
mbed-gr-libs/GraphicsFramework/ospl/porting \
mbed-gr-libs/GraphicsFramework/ospl/src \
mbed-gr-libs/R_BSP/RenesasBSP/drv_src/TARGET_RZ_A1XX/dma \
mbed-gr-libs/R_BSP/RenesasBSP/drv_src/TARGET_RZ_A1XX/scux \
mbed-gr-libs/R_BSP/RenesasBSP/drv_src/TARGET_RZ_A1XX/ssif \
mbed-gr-libs/R_BSP/RenesasBSP/drv_src/ioif \
mbed-gr-libs/R_BSP/common \
mbed-gr-libs/R_BSP/tools \
mbed-gr-libs/SDBlockDevice_GRBoard/TARGET_RZ_A1XX/sd-driver-master \
mbed-gr-libs/SDBlockDevice_GRBoard/TARGET_RZ_A1XX/sd-driver-master/util \
mbed-gr-libs/USBDevice/USBAudio \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/common \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/function \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/userdef \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/common \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/function \
mbed-gr-libs/USBDevice/USBDevice/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/userdef \
mbed-gr-libs/USBDevice/USBDevice \
mbed-gr-libs/USBDevice/USBHID \
mbed-gr-libs/USBDevice/USBMIDI \
mbed-gr-libs/USBDevice/USBMSD \
mbed-gr-libs/USBDevice/USBSerial \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/common \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/host \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb0/src/userdef \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/common \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/host \
mbed-gr-libs/USBHost_custom/USBHost/TARGET_RENESAS/TARGET_RZ_A1XX/usb1/src/userdef \
mbed-gr-libs/USBHost_custom/USBHost \
mbed-gr-libs/USBHost_custom/USBHost3GModule \
mbed-gr-libs/USBHost_custom/USBHostHID \
mbed-gr-libs/USBHost_custom/USBHostHub \
mbed-gr-libs/USBHost_custom/USBHostMIDI \
mbed-gr-libs/USBHost_custom/USBHostMSD \
mbed-gr-libs/USBHost_custom/USBHostSerial \
mbed-gr-libs/bd/RomRamBlockDevice \
mbed-gr-libs/components/AUDIO/MAX9867_RBSP \
mbed-gr-libs/components/AUDIO/PwmOutSpeaker \
mbed-gr-libs/components/AUDIO/SoundlessSpeaker \
mbed-gr-libs/components/AUDIO/TLV320_RBSP \
mbed-gr-libs/components/AUDIO/WM8978_RBSP \
mbed-gr-libs/components/LCD/Display_shield_config \
mbed-gr-libs/components/LCD/LCD_config_lychee \
mbed-gr-libs/components/LCD/LCD_shield_config/LcdCfg_LCD_shield \
mbed-gr-libs/components/LCD/LCD_shield_config/TouchKey_LCD_shield \
mbed-gr-libs/components/WIFI/esp32-driver/ESP32 \
mbed-gr-libs/components/WIFI/esp32-driver \
mbed-gr-libs/dcache-control \
mbed-os/cmsis/TARGET_CORTEX_A \
mbed-os/drivers \
mbed-os/events \
mbed-os/events/equeue \
mbed-os/features/device_key/source \
mbed-os/features/frameworks/greentea-client/source \
mbed-os/features/frameworks/mbed-client-cli/source \
mbed-os/features/frameworks/mbed-client-randlib/source \
mbed-os/features/frameworks/mbed-coap/source \
mbed-os/features/frameworks/mbed-trace/source \
mbed-os/features/frameworks/nanostack-libservice/source/IPv6_fcf_lib \
mbed-os/features/frameworks/nanostack-libservice/source/libBits \
mbed-os/features/frameworks/nanostack-libservice/source/libList \
mbed-os/features/frameworks/nanostack-libservice/source/libip4string \
mbed-os/features/frameworks/nanostack-libservice/source/libip6string \
mbed-os/features/frameworks/nanostack-libservice/source/nsdynmemLIB \
mbed-os/features/frameworks/nanostack-libservice/source/nvmHelper \
mbed-os/features/frameworks/unity/source \
mbed-os/features/frameworks/utest \
mbed-os/features/frameworks/utest/source \
mbed-os/features/mbedtls/platform/src \
mbed-os/features/mbedtls/src \
mbed-os/features/mbedtls/targets \
mbed-os/features/netsocket \
mbed-os/features/storage/blockdevice \
mbed-os/features/storage/filesystem \
mbed-os/features/storage/filesystem/fat/ChaN \
mbed-os/features/storage/filesystem/fat \
mbed-os/features/storage/filesystem/littlefs \
mbed-os/features/storage/filesystem/littlefs/littlefs \
mbed-os/features/storage/nvstore/source \
mbed-os/features/storage/system_storage \
mbed-os/hal \
mbed-os/platform \
mbed-os/rtos \
mbed-os/rtos/TARGET_CORTEX \
mbed-os/rtos/TARGET_CORTEX/TOOLCHAIN_GCC_ARM \
mbed-os/rtos/TARGET_CORTEX/rtx4 \
mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config \
mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/TARGET_CORTEX_A \
mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_CORTEX_A \
mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source \
mbed-os/rtos/TARGET_CORTEX/rtx5/Source \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_GCC_ARM \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/common \
utilities/HttpServer_snapshot_mbed-os \
utilities/HttpServer_snapshot_mbed-os/Handler \
utilities \
utilities/mbed-http/http_parser \
utilities/mbed-rpc \

