script:
      # Check that examples compile
    - sed -n '/``` cpp/,${/```$/q;/```/d;p}' README.md > main.cpp &&
      PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM -m K64F
          --source=. --build=BUILD/K64F/GCC_ARM -j0 &&
      rm main.cpp

      # Check that tests compile
    - rm -rf BUILD && PYTHONPATH=mbed-os python mbed-os/tools/test.py
          -t GCC_ARM -m K64F --source=. --build=BUILD/TESTS/K64F/GCC_ARM -j0
          -n tests*

python:
    - "2.7"

install:
      # Get arm-none-eabi-gcc
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
      # Get dependencies
    - git clone https://github.com/armmbed/mbed-os.git
      # Install python dependencies
    - pip install --user -r mbed-os/requirements.txt
